# Site Info
title: Think Tank
tagline: Think Tank
description: 이것저것 기술블로그
baseurl: ""
url: http://kizuc.github.io
logo: '/public/img/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: kizuc
  description:  Running Up That Hill
  # gravatar: # md5 hash of your email address
  contact:
    github:    https://github.com/kizuc
    email:    kizucc@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/blog/categories/'
    - { TIL : '/blog/categories/#til' }
    - { database : '/blog/categories/#database' }
    - { java : '/blog/categories/#java' }
    - { jsp : '/blog/categories/#jsp' }
    - { report : '/blog/categories/#report' }
    - { etc : '/blog/categories/#etc' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

milkyway:
  image: /public/img/ham.png
  caption: Running Up That Hill

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus

