# Site Info
title: [블로그 타이틀]
tagline: [블로그 부제목]
description: [블로그 설명]
baseurl: ''
url: https://kizuc.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: kizuc
  description: 랄랄라
  contact:
    # linkedin:  <hide>
    github:    https://github.com/kizuc
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    email:     kizucc@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Search: 
    - '/searc/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus

