# Site Info
title: Think Tank
tagline: 'Think Tank'
description: '이것저것 기술하는 블로그'
baseurl: ""
url: http://kizuc.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: kizuc
  description: <strong>Running Up That Hill</strong>
  #gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/kizuc
    #facebook:  <hide>
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    email:     kizucc@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/blog/'
  Categories:           
    - '/blog/categories'
    - { TIL: '/blog/#TIL' }
    - { etc: '/blog/#etc' }
    - { report: '/blog/#report' }
    - { Tags: '/blog/tags/' }
  # Report:          
  #  - '/about/'
  # Github Project: 
  #  - 'http://v.github.io/'
  # Search:
  #  - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/ham.png
  # caption: Original Artwork &copy; deang

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus

exclude: [vendor]
